const DISPLAY_ALERT = 'SHOW_ALERT';
const CLEAR_ALERT = 'CLEAR_ALERT';
const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
const ERROR = 'ERROR';
const START_LOADING = 'START_LOADING';
const STOP_LOADING = 'STOP_LOADING';
const TOGGLE_LOAD = 'TOGGLE_LOAD';

export {
  DISPLAY_ALERT,
  CLEAR_ALERT,
  SUBSCRIBE_SUCCESS,
  ERROR,
  START_LOADING,
  STOP_LOADING,
  TOGGLE_LOAD,
};
